baseURL: https://vpatel95.github.io

languageCode: en-us
title: "Ved Patel"
theme: "toha"


languages:
    en:
        languageName: English
        weight: 1

markup:
    tableOfContents:
        startLevel: 2
        endLevel: 6
        ordered: false

enableEmoji: true

params:
    gitRepo: https://github.com/vpatel95/vpatel95.github.io
    enableBlogPost: false
    logo:
        inverted: "images/logo_white.png"
        main: "images/logo_black.png"
        favicon: "images/logo_black.png"

